CSV_EXTENSION = "csv"
JSON_EXTENSION = "json"
VALUE_SEPARATOR = ";"


STATUS_PENDING = "PENDING"
STATUS_NOT_FOUND = "NOT_FOUND"
STATUS_DOWNLOADED = "DOWNLOADED"
STATUS_BUILDING = "BUILDING"
STATUS_PROCESSED = "PROCESSED"
