CSV_EXTENSION = "csv"
JSON_EXTENSION = "json"
VALUE_SEPARATOR = ";"


STATUS_PENDING = "PENDING"
STATUS_NOT_FOUND = "NOT_FOUND"
STATUS_DOWNLOADED = "DOWNLOADED"
STATUS_BUILDING = "BUILDING"
STATUS_PROCESSED = "PROCESSED"


ERROR_INVALIDSCHEMA_SD = 1701
ERROR_INVALIDSCHEMA_DD = 1702
ERROR_DESERIALIZATION_SD = 1703
ERROR_DESERIALIZATION_DD = 1704

